#!/usr/bin/python3
"""Returning the location of the ISS in latitude/longitude"""
import requests
import datetime

URL= "http://api.open-notify.org/iss-now.json"
def main():
    resp= requests.get(URL).json()
    timestamp = datetime.datetime.fromtimestamp(resp["timestamp"])
    print("CURRENT LOCATION OF THE ISS")
    print("Timestamp: ", timestamp) 
    print("Lon ", resp["iss_position"]["latitude"])
    print("Lat ", resp["iss_position"]["longitude"])
if __name__ == "__main__":
    main()

